### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by samuelmolinski** [bmcclure/kalabox-plugin-drupal-console#3]
I get this error when running `kbox drupal`

```
PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /src/code/vendor/drupal/console-core/src/Utils/DrupalFinder.php:24
Stack trace:
#0 /src/code/vendor/drupal/console/bin/drupal.php(37): Drupal\Console\Core\Utils\DrupalFinder->locateRoot('/src/code')
#1 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/src/code/vendo...')
#2 phar:///usr/local/bin/drupal/bin/drupal.php(86): Drupal\Console\Launcher\Utils\Launcher->launch('/src/code', Object(Composer\Autoload\ClassLoader))
#3 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#4 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#5 {main}
  thrown in /src/code/vendor/drupal/console-core/src/Utils/DrupalFinder.php on line 24

Fatal error: Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir() in /src/code/vendor/drupal/console-core/src/Utils/DrupalFinder.php:24
Stack trace:
#0 /src/code/vendor/drupal/console/bin/drupal.php(37): Drupal\Console\Core\Utils\DrupalFinder->locateRoot('/src/code')
#1 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/src/code/vendo...')
#2 phar:///usr/local/bin/drupal/bin/drupal.php(86): Drupal\Console\Launcher\Utils\Launcher->launch('/src/code', Object(Composer\Autoload\ClassLoader))
#3 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#4 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#5 {main}
  thrown in /src/code/vendor/drupal/console-core/src/Utils/DrupalFinder.php on line 24
```

I have confirmed that webflo is installed in the vendor folder.  I have tried to run a few more commands like `kbox drupal self-update` and have the same issue.  I am kind of clueless how to fix this, any help would be welcome.

**Comment by ReplicaObscura** [comment]
Hm, I have not run into this issue myself, but it seems like perhaps an issue with either the docker container being used for the plugin (maybe it's changed since I last installed it), or perhaps it didn't build correctly in which case `kbox rebuild` might take care of it.

**Comment by panarican** [comment]
I get the same error I tried kbox rebuild and it didn't seem to work :(

**Comment by ultimike** [comment]
I am getting the exact same error as well when running `kbox drupal init` after installing the plugin.

In my case, I'm using a nested docroot. Are there any config changes I need to make within the plugin to support this? I was thinking that there might be one in `drupal-console-cli.yml` (the `mapping` parameter?)

-mike

**Comment by RichardCheung** [comment]
I guess the packages inside the drupalconsole docker image has version mismatch between the `webflo/drupal-finder` and the `drupal/console`.
The latest version of `drupal/console` (currently 1.0.0-rc25) depends on  `webflo/drupal-finder:0.3.0`.

If you add the function manually as below to vendor/drupal/console-core/src/Utils/DrupalFinder.php, `kbox drupal` will run again.
```
/**
 * @return string
 */
public function getVendorDir()
{
    return parent::getDrupalRoot() . 'vendor';
}
```
Since this `DrupalFinder::getVendorDir()` function was added in version 0.3.0, this work around is to hard code the vendor path as a temp solution.

I am not familiar with docker so someone may point out the proper way to resolve it by updating the docker image / Dockerfile.

**Comment by ReplicaObscura** [comment]
Thanks for figuring this out! I was starting to run into this myself. Not sure when I'll have time exactly, but I may be able to take a crack at updating the docker image soon.

**Comment by mortona42** [comment]
Fixed for me, thanks!

**Comment by christhorp** [comment]
I tried adding the function but now I get the error:

`Fatal error: Declaration of Drupal\Component\DependencyInjection\Container::set($id, $service) must be compatible with Symfony\Component\DependencyInjection\ContainerInterface::set($id, $service, $scope = self::SCOPE_CONTAINER) in /src/code/core/lib/Drupal/Component/DependencyInjection/Container.php on line 47`
